# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=32)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('1', 'Conta Corrente'), ('2', 'Conta Poupança')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('1', 'Crédito'), ('2', 'Débito')], max_length=2)),
                ('descricao', models.CharField(max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.ContaBanco')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa.Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
