# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_lancamentosbanco_id_conta_a_pagar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentosbanco',
            old_name='id_conta_a_pagar',
            new_name='conta_a_pagar',
        ),
    ]
