# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_lancamentosbanco_conta_a_receber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabanco',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
