# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='usuarioprofile',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto_perfil/'),
        ),
    ]
