# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_receber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contasareceber',
            old_name='recebida',
            new_name='recebido',
        ),
    ]
