# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_receber', '0002_auto_20171221_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasareceber',
            name='descricao',
            field=models.CharField(max_length=64),
        ),
    ]
