# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_receber', '0003_auto_20171222_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasareceber',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
