# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_receber', '0004_contasareceber_data_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contasareceber',
            old_name='data_pagamento',
            new_name='data_recebimento',
        ),
    ]
