# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
                ('tipo', models.CharField(choices=[('1', 'Entrada'), ('2', 'SAIDA')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa.Categoria')),
            ],
        ),
    ]
