# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0001_initial'),
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoscaixa',
            name='id_conta_a_pagar',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='contas_a_pagar.ContasAPagar'),
            preserve_default=False,
        ),
    ]
