# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lancamentoscaixa',
            name='descricao',
            field=models.CharField(max_length=32),
        ),
    ]
