# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa', '0002_auto_20171001_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoscaixa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
