# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_receber', '0003_auto_20171222_1111'),
        ('caixa', '0004_auto_20171203_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoscaixa',
            name='conta_a_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas_a_receber.ContasAReceber'),
        ),
    ]
