# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_lancamentoscaixa_conta_a_receber'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='padrao',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
