# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='tipo_conta',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
