# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0002_contasapagar_tipo_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
