# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarMetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('titulo', models.CharField(max_length=40)),
                ('valor', models.DecimalField(decimal_places=9, max_digits=9)),
            ],
        ),
    ]
