# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarmetas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
