# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metas', '0002_auto_20171115_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrarmetas',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
