# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_cadastrarmetas_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastrarMetas',
            new_name='Metas',
        ),
    ]
