# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_auto_20171115_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metas',
            name='progresso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
