# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_auto_20171115_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='progresso',
            field=models.IntegerField(default=0),
        ),
    ]
