# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0009_auto_20171119_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
