# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0010_auto_20171220_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
