# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0011_auto_20171226_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='dataFim',
        ),
        migrations.RemoveField(
            model_name='metas',
            name='dataInicio',
        ),
        migrations.AlterField(
            model_name='metas',
            name='progresso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
