# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0013_auto_20190210_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='progresso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
